### ISSUE TITLE
Команда для Ubuntu в інструкції не вірна

### ISSUE THREAD

**Issue by o10g** [neochief/ukrainian-typographic-layouts#1]
Перш за все хочу виказати подяку за розкладки і можливість встановити на Ubuntu, цього дуже не вистачало.

У команді запуску на Ubuntu декілька помилок.
1. директорія у яку розпаковується командою у мене така:
`/tmp/ukrainian-typographic-layouts-master/`

2. Запускати команду потрібно не з кореню, але з 
`/tmp/ukrainian-typographic-layouts-master/Ubuntu`
Якщо робити це з кореню, то install.sh не бачить файлів, які потрібні для встановлення розкладки.

**Comment by neochief** [comment]
Дякую! Інструкцію поновив.
