### ISSUE TITLE
А як зробити, щоб і на лівий alt працювало?

### ISSUE THREAD

**Issue by oleedd** [neochief/ukrainian-typographic-layouts#5]

**Comment by ALERTua** [comment]
це не питання до цього проекту. ваш гугл запит — "windows left alt as altgr" або "windows remap altgr". ваша ціль — змінити функцію лівого альта з Alt на AltGR.
наприклад: https://www.thewindowsclub.com/how-do-i-enable-or-disable-alt-gr-key-on-windows-10-keyboard

**Comment by oleedd** [comment]
Ні, для remap потрібно, щоб у треї постійно працювала програма, це так собі. Мене цікавить, як у сам файл розкладки додати ще лівий alt (щоб не тягнутися від правого до деяких клавіш, що незручно).

**Comment by neochief** [comment]
Людина вам сказала правду, це технічно неможливо зробити саме розкладкою.

**Comment by oleedd** [comment]
@neochief
Чому технічно неможливо? Хіба Windows не підтримує лівий alt? Хочу модифікувати файл розкладки.
